// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooAPI.Data;

#nullable disable

namespace ZooAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooCore.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 5,
                            Description = "L’’alligator est un grand reptile, c’est même l’un des plus gros crocodilien au monde, pouvant atteindre jusqu’à 4,5 mètres et peser plus de 450 kilos.",
                            ImageUrl = "/images/Alligator.webp",
                            Name = "Guillaume",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            Description = "La chauve-souris, aussi appelée « roussette » ou « renard volant », est une espèce du genre des Pteropus, une branche des « mégachiroptères ». Endémique de l’île de Rodrigues, ce mammifère volant atteint une taille et une envergure assez conséquentes : son corps mesure 15 à 20 cm et son envergure est de 50 à 90 cm. Elle pèse généralement entre 300 et 350 grammes.",
                            ImageUrl = "/images/ChauveSouris.webp",
                            Name = "Clemence",
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 3,
                            Age = 10,
                            Description = "Le panda géant vit dans les régions montagneuses de Chine, entre 1 200 et 4 100 mètres d'altitude. Bien qu'il soit classé parmi les mammifères carnivores, il mange presque exclusivement des pousses de bambou.",
                            ImageUrl = "/images/Panda.webp",
                            Name = "Remy",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 4,
                            Age = 17,
                            Description = "De la famille des hominidés, le chimpanzé commun peut vivre jusqu’à 50/60 ans et peser 40 à 65 kg. Lointain cousin des humains, il partage avec nous de nombreuses similarités.",
                            ImageUrl = "/images/Chimpanze.webp",
                            Name = "Johnny",
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 5,
                            Age = 6,
                            Description = "Pouvant mesurer jusqu’à 3,10 mètres de long et peser jusqu’à 165 kg, le dragon (ou varan) de Komodo est le lézard le plus grand du monde. Très trapu, ce reptile de la famille des varanidés à l’allure imposante est doté d’une cuirasse et d’une queue extrêmement musclée.",
                            ImageUrl = "/images/DragonKomodo.webp",
                            Name = "Gregory",
                            SpeciesId = 14
                        },
                        new
                        {
                            Id = 6,
                            Age = 1,
                            Description = "Le gorille est le plus gros singe semblable à l’Homme au monde. Les mâles peuvent peser jusqu’à 250 kg ! Le mâle adulte présente une stature beaucoup plus imposante que la femelle. Sa tête est beaucoup plus volumineuse et, à l’âge adulte, le dos des mâles se colore de gris.",
                            ImageUrl = "/images/Gorille.webp",
                            Name = "Kevin",
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 7,
                            Age = 2,
                            Description = "L'éléphant d'Afrique des savanes peut peser plus de 7 tonnes et mesurer jusqu'à 4 mètres de hauteur. Les seuls animaux pouvant rivaliser avec lui au concours de l’animal le plus lourd sont les cétacés, comme la baleine bleue… Aucun mammifère terrestre n’est à la hauteur.",
                            ImageUrl = "/images/Elephant.webp",
                            Name = "Gaetan",
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 8,
                            Age = 3,
                            Description = "De la famille des Hippopotamidae, ce géant semi-aquatique peut peser jusqu’à 3 tonnes et vivre 40 à 50 ans ! Un nouveau-né pèse environ 50 kg à la naissance.L’hippopotame vit principalement dans les rivières, les lacs ou les fleuves, comme le Nil, à proximité de pâturages où il trouve sa nourriture quand vient le soir.",
                            ImageUrl = "/images/Hippopotame.webp",
                            Name = "Adrien",
                            SpeciesId = 9
                        },
                        new
                        {
                            Id = 9,
                            Age = 4,
                            Description = "La girafe est un animal très social, vivant en groupe de 5 à 20 individus dans les savanes africaines. La vie en communauté permet de repérer les prédateurs et se défendre de leurs attaques.",
                            ImageUrl = "/images/Girafe.webp",
                            Name = "Malik",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 10,
                            Age = 9,
                            Description = "Le diable de Tasmanie, mammifère endémique de l’île de Tasmanie au sud de l’Océanie, est aujourd’hui le plus grand marsupial carnivore d’Australie, bien qu’il ne dépasse pas la taille d’un chien. En dépit de son apparence, de son alimentation et de son nom, le diable de Tasmanie est en réalité timide, méfiant et ne s’attaque à l’Homme que s’il se sent menacé.",
                            ImageUrl = "/images/DiableTasmanie.webp",
                            Name = "Slimane",
                            SpeciesId = 15
                        },
                        new
                        {
                            Id = 11,
                            Age = 7,
                            Description = "Le charisme et l’apparence majestueuse du lion lui ont donné le surnom de roi des animaux. Ce grand prédateur veille en véritable monarque sur son territoire et sa cour, composée de lionnes et leurs petits. Ce sont ces femelles qui assurent l’essentiel des chasses et approvisionnent le groupe.",
                            ImageUrl = "/images/Lion.webp",
                            Name = "Anthony",
                            SpeciesId = 10
                        },
                        new
                        {
                            Id = 12,
                            Age = 2,
                            Description = "Souvent confondu avec le toucan à cause de son gigantesque bec, le calao rhinocéros se différencie pourtant par une particularité notable : son casque. Surmontant le bec comme une corne, le casque des calaos varie en taille et en couleur selon l’espèce.",
                            ImageUrl = "/images/Calao.webp",
                            Name = "Thomas",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 13,
                            Age = 2,
                            Description = "Souvent confondu avec le toucan à cause de son gigantesque bec, le calao rhinocéros se différencie pourtant par une particularité notable : son casque. Surmontant le bec comme une corne, le casque des calaos varie en taille et en couleur selon l’espèce.",
                            ImageUrl = "/images/Calao.webp",
                            Name = "Carole",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 14,
                            Age = 7,
                            Description = "L'éléphant d'Afrique des savanes peut peser plus de 7 tonnes et mesurer jusqu'à 4 mètres de hauteur. Les seuls animaux pouvant rivaliser avec lui au concours de l’animal le plus lourd sont les cétacés, comme la baleine bleue… Aucun mammifère terrestre n’est à la hauteur.",
                            ImageUrl = "/images/Elephant.webp",
                            Name = "Nicolas",
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 15,
                            Age = 1,
                            Description = "La girafe est un animal très social, vivant en groupe de 5 à 20 individus dans les savanes africaines. La vie en communauté permet de repérer les prédateurs et se défendre de leurs attaques.",
                            ImageUrl = "/images/Girafe.webp",
                            Name = "Aicha",
                            SpeciesId = 6
                        });
                });

            modelBuilder.Entity("ZooCore.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alligator",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Calao",
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chimpanzé",
                            Status = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chauve-souris",
                            Status = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eléphant d'Afrique",
                            Status = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Girafe",
                            Status = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gorille",
                            Status = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Guépard",
                            Status = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hippopotame",
                            Status = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lion",
                            Status = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Panda",
                            Status = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dragon de Komodo",
                            Status = 4
                        },
                        new
                        {
                            Id = 15,
                            Name = "Diable de Tasmanie",
                            Status = 4
                        });
                });

            modelBuilder.Entity("ZooCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4 Avenue de l'Horizon 59650 Villeneuve d'Ascq",
                            Email = "iabadi@zooclemy.fr",
                            FirstName = "Ihab",
                            LastName = "Abadi",
                            Password = "U3VwZXJaMDArK09TRmMuX09kVUE0cWZjI3tRQWJY",
                            PhoneNumber = "0679486132"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5 rue des Coquelicots 59650 Villeneuve d'Ascq",
                            Email = "jdoe@zooclemy.fr",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "MGhsYWxhaidhaTB1Ymxpw6khT1NGYy5fT2RVQTRxZmMje1FBYlg=",
                            PhoneNumber = "0789543354"
                        });
                });

            modelBuilder.Entity("ZooCore.Models.Animal", b =>
                {
                    b.HasOne("ZooCore.Models.Species", "Species")
                        .WithMany("Animals")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooCore.Models.Species", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
